#!/usr/bin/env node
/**
 * Automatic Skill — Stage 7: Upload (上传)
 * 输出 Agent 执行 prompt，指导其将新 skill commit 推送到 GitHub 并发布到 clawHub。
 *
 * 用法:
 *   node scripts/upload.js <skill-dir>
 *   node scripts/upload.js --from-pipeline
 *   node scripts/upload.js --dry-run --from-pipeline   (仅预览，不实际上传)
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const langIdx = args.indexOf('--lang');
const lang = langIdx !== -1 ? args[langIdx + 1] : 'zh';
const dryRun = args.includes('--dry-run');

let skillDir = '';
let slug = '';
if (args.includes('--from-pipeline')) {
  const pipelinePath = path.join(__dirname, '..', 'data', 'current-pipeline.json');
  if (fs.existsSync(pipelinePath)) {
    const p = JSON.parse(fs.readFileSync(pipelinePath, 'utf8'));
    skillDir = (p.create && p.create.skillDir) || '';
    slug = (p.design && p.design.slug)
      || (p.research && p.research.selected && p.research.selected.slug)
      || path.basename(skillDir);
  }
}
if (!skillDir) {
  skillDir = args.filter(a => a !== '--lang' && a !== lang && !a.startsWith('--'))[0] || '';
  slug = path.basename(skillDir);
}
if (!skillDir) {
  console.error('Usage: node scripts/upload.js <skill-dir>');
  console.error('       node scripts/upload.js --from-pipeline');
  process.exit(1);
}

const githubRepo = process.env.GITHUB_REPO || '<GITHUB_REPO not set>';
const dryRunNote = dryRun ? '\n⚠️  DRY-RUN MODE: Print commands but DO NOT execute git push or clawhub publish.' : '';

if (lang === 'en') {
  console.log(`
=== AUTOMATIC SKILL — Stage 7: Upload ===
Skill: ${slug}
Skill directory: ${skillDir}
GitHub repo: ${githubRepo}
${dryRunNote}

Upload the skill to GitHub and clawHub. Follow all steps in order.

── PART 1: GitHub Upload ─────────────────────────────────────────

STEP 1 — Check environment
Verify GITHUB_TOKEN is set: echo $GITHUB_TOKEN (should print a token, not empty)
Verify GITHUB_REPO is set: echo $GITHUB_REPO (should print "owner/repo")

STEP 2 — Navigate to the skills repository root
If the skills repo is a separate git repository, cd into its root.
If the skills live inside an existing repo, cd to that repo root.

STEP 3 — Copy/confirm skill directory
Ensure the skill directory exists at the correct path within the repo.
If it's not inside the repo, copy it: cp -r ${skillDir} <repo-root>/openclaw/agents/skills/${slug}

STEP 4 — Stage and commit
git add openclaw/agents/skills/${slug}/
git status  (confirm only the new skill files are staged)
git commit -m "feat: add ${slug} skill — auto-generated by automatic-skill pipeline $(date +%Y-%m-%d)"

STEP 5 — Push${dryRun ? ' (SKIPPED — dry-run)' : ''}
${dryRun ? 'DRY-RUN: would run: git push origin main' : 'git push origin main'}

Record the commit hash: git rev-parse HEAD

── PART 2: clawHub Publish ──────────────────────────────────────

STEP 6 — Check clawHub token
Verify CLAWHUB_TOKEN is set: echo $CLAWHUB_TOKEN

STEP 7 — Publish to clawHub${dryRun ? ' (SKIPPED — dry-run)' : ''}
${dryRun
  ? 'DRY-RUN: would run clawhub publish command'
  : `Run the clawhub CLI publish command for the skill:
  clawhub publish ${skillDir}
  (If clawhub CLI is not installed, use the API directly:
   curl -X POST https://api.clawhub.io/v1/skills/publish \\
     -H "Authorization: Bearer $CLAWHUB_TOKEN" \\
     -H "Content-Type: application/json" \\
     -d @${skillDir}/SKILL.md )`}

STEP 8 — Record clawHub publish response
Save the publish response (especially the skill ID or version returned).

── OUTPUT FORMAT (JSON) ─────────────────────────────────────────
{
  "stage": "upload",
  "skillDir": "${skillDir}",
  "slug": "${slug}",
  "dryRun": ${dryRun},
  "github": {
    "repo": "${githubRepo}",
    "commitHash": "...",
    "branch": "main",
    "status": "SUCCESS" | "FAILED" | "SKIPPED",
    "error": null
  },
  "clawhub": {
    "publishedVersion": "...",
    "status": "SUCCESS" | "FAILED" | "SKIPPED",
    "error": null
  },
  "completedAt": "<ISO timestamp>"
}

If any part FAILED: record the error and stop. Do not proceed.
If SUCCESS or SKIPPED (dry-run): proceed to Stage 8: node scripts/verify-upload.js ${slug}

Update data/current-pipeline.json: add "upload" key with the report above.
`);
} else {
  console.log(`
=== AUTOMATIC SKILL — 阶段 7：上传 ===
Skill：${slug}
Skill 目录：${skillDir}
GitHub 仓库：${githubRepo}
${dryRunNote}

将 skill 上传到 GitHub 和 clawHub。按顺序执行所有步骤。

── 第一部分：GitHub 上传 ──────────────────────────────────────────

步骤 1 — 检查环境变量
验证 GITHUB_TOKEN 已设置：echo $GITHUB_TOKEN（应打印 token，非空）
验证 GITHUB_REPO 已设置：echo $GITHUB_REPO（应打印 "owner/repo"）

步骤 2 — 进入 skills 仓库根目录
如果 skills 仓库是独立的 git 仓库，cd 到其根目录。
如果 skills 在现有仓库中，cd 到该仓库根目录。

步骤 3 — 复制/确认 skill 目录
确认 skill 目录在仓库内的正确路径存在。
如果不在仓库内，复制过去：cp -r ${skillDir} <repo-root>/openclaw/agents/skills/${slug}

步骤 4 — 暂存并提交
git add openclaw/agents/skills/${slug}/
git status（确认只有新 skill 文件被暂存）
git commit -m "feat: add ${slug} skill — auto-generated by automatic-skill pipeline $(date +%Y-%m-%d)"

步骤 5 — 推送${dryRun ? '（已跳过 — dry-run）' : ''}
${dryRun ? 'DRY-RUN：将运行：git push origin main' : 'git push origin main'}

记录 commit hash：git rev-parse HEAD

── 第二部分：clawHub 发布 ────────────────────────────────────────

步骤 6 — 检查 clawHub token
验证 CLAWHUB_TOKEN 已设置：echo $CLAWHUB_TOKEN

步骤 7 — 发布到 clawHub${dryRun ? '（已跳过 — dry-run）' : ''}
${dryRun
  ? 'DRY-RUN：将运行 clawhub publish 命令'
  : `运行 clawhub CLI 发布命令：
  clawhub publish ${skillDir}
  （如未安装 clawhub CLI，直接调用 API：
   curl -X POST https://api.clawhub.io/v1/skills/publish \\
     -H "Authorization: Bearer $CLAWHUB_TOKEN" \\
     -H "Content-Type: application/json" \\
     -d @${skillDir}/SKILL.md )`}

步骤 8 — 记录 clawHub 发布响应
保存发布响应（尤其是返回的 skill ID 或版本号）。

── 输出格式（JSON）────────────────────────────────────────────────
{
  "stage": "upload",
  "skillDir": "${skillDir}",
  "slug": "${slug}",
  "dryRun": ${dryRun},
  "github": {
    "repo": "${githubRepo}",
    "commitHash": "...",
    "branch": "main",
    "status": "SUCCESS" | "FAILED" | "SKIPPED",
    "error": null
  },
  "clawhub": {
    "publishedVersion": "...",
    "status": "SUCCESS" | "FAILED" | "SKIPPED",
    "error": null
  },
  "completedAt": "<ISO 时间戳>"
}

如果任何部分 FAILED：记录错误并停止，不继续。
如果 SUCCESS 或 SKIPPED（dry-run）：进入阶段 8：node scripts/verify-upload.js ${slug}

更新 data/current-pipeline.json：添加 "upload" 键，值为上述报告。
`);
}
